// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/ada1df33d63c1cc16a18240d15e4df46974c9914/method-override/index.d.ts
declare module 'method-override' {
// Type definitions for method-override
// Project: https://github.com/expressjs/method-override
// Definitions by: Santi Albo <https://github.com/santialbo/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped



namespace Express {
    export interface Request {
        originalMethod?: string;
    }
}

import express = require('express');

namespace e {
    export interface MethodOverrideOptions {
        methods: string[];
    }
}

function e(getter?: string, options?: e.MethodOverrideOptions): express.RequestHandler;
function e(getter?: string | ((req: express.Request, res: express.Response) => string), options?: e.MethodOverrideOptions): express.RequestHandler;

export = e;
}
